name: deeplsh-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=23.3.1
  - setuptools>=64
  - numpy=1.19.5
  - pandas=1.2.4
  - scikit-learn=0.24.2
  - scipy=1.7.0
  - h5py=3.1.0
  - grpcio=1.34.1
  - requests
  - chardet
  # Dev / notebook tooling
  - matplotlib=3.4.2
  - seaborn=0.11.1
  - jupyterlab
  - pip:
      - tensorflow-macos==2.5.0
      - pylev==1.4.0
      - fnvhash==0.2.1
